# Setup
name:         Package Templates
tagline:      Plugin for Intellij IDEA
baseurl:      "/PackageTemplates"

# Gems
gems:
  - jekyll-paginate
  - markdown_converter

#Others
markdown: kramdown