# Setup
name:         Package Templates
tagline:      Plugin for Intellij IDEA
baseurl:      "/PackageTemplates"

collections:
-  tutorials:
     output: true

# Gems
gems:
- jekyll-paginate

#Others
markdown: kramdown